# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/example/arty.xdc

# IP: ip/aee_rom/aee_rom.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==aee_rom || ORIG_REF_NAME==aee_rom} -quiet] -quiet
