# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "R:/Users/Mitchell/Documents/Academics/PotatoProcessor/PotatoProcessor.runs/synth_1/toplevel.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 6
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7s50csga324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir R:/Users/Mitchell/Documents/Academics/PotatoProcessor/PotatoProcessor.cache/wt [current_project]
set_property parent.project_path R:/Users/Mitchell/Documents/Academics/PotatoProcessor/PotatoProcessor.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib work [current_project]
set_property target_language VHDL [current_project]
set_property board_part_repo_paths {C:/Users/Mitchell/AppData/Roaming/Xilinx/Vivado/2020.2/xhub/board_store/xilinx_board_store} [current_project]
set_property board_part digilentinc.com:arty-s7-50:part0:1.0 [current_project]
set_property ip_output_repo r:/Users/Mitchell/Documents/Academics/PotatoProcessor/PotatoProcessor.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files {{R:/Users/Mitchell/Documents/Academics/PotatoProcessor/PotatoProcessor.srcs/sources_1/imports/Potato Processor/bootloader.coe}}
read_vhdl -library work {
  R:/Users/Mitchell/Documents/Academics/PotatoProcessor/PotatoProcessor.srcs/sources_1/imports/potato/src/pp_types.vhd
  R:/Users/Mitchell/Documents/Academics/PotatoProcessor/PotatoProcessor.srcs/sources_1/imports/potato/src/pp_constants.vhd
  R:/Users/Mitchell/Documents/Academics/PotatoProcessor/PotatoProcessor.srcs/sources_1/imports/potato/src/pp_utilities.vhd
  R:/Users/Mitchell/Documents/Academics/PotatoProcessor/PotatoProcessor.srcs/sources_1/imports/potato/example/aee_rom_wrapper.vhd
  R:/Users/Mitchell/Documents/Academics/PotatoProcessor/PotatoProcessor.srcs/sources_1/imports/potato/src/pp_alu.vhd
  R:/Users/Mitchell/Documents/Academics/PotatoProcessor/PotatoProcessor.srcs/sources_1/imports/potato/src/pp_alu_control_unit.vhd
  R:/Users/Mitchell/Documents/Academics/PotatoProcessor/PotatoProcessor.srcs/sources_1/imports/potato/src/pp_alu_mux.vhd
  R:/Users/Mitchell/Documents/Academics/PotatoProcessor/PotatoProcessor.srcs/sources_1/imports/potato/src/pp_comparator.vhd
  R:/Users/Mitchell/Documents/Academics/PotatoProcessor/PotatoProcessor.srcs/sources_1/imports/potato/src/pp_csr.vhd
  R:/Users/Mitchell/Documents/Academics/PotatoProcessor/PotatoProcessor.srcs/sources_1/imports/potato/src/pp_control_unit.vhd
  R:/Users/Mitchell/Documents/Academics/PotatoProcessor/PotatoProcessor.srcs/sources_1/imports/potato/src/pp_counter.vhd
  R:/Users/Mitchell/Documents/Academics/PotatoProcessor/PotatoProcessor.srcs/sources_1/imports/potato/src/pp_csr_unit.vhd
  R:/Users/Mitchell/Documents/Academics/PotatoProcessor/PotatoProcessor.srcs/sources_1/imports/potato/src/pp_register_file.vhd
  R:/Users/Mitchell/Documents/Academics/PotatoProcessor/PotatoProcessor.srcs/sources_1/imports/potato/src/pp_fetch.vhd
  R:/Users/Mitchell/Documents/Academics/PotatoProcessor/PotatoProcessor.srcs/sources_1/imports/potato/src/pp_imm_decoder.vhd
  R:/Users/Mitchell/Documents/Academics/PotatoProcessor/PotatoProcessor.srcs/sources_1/imports/potato/src/pp_decode.vhd
  R:/Users/Mitchell/Documents/Academics/PotatoProcessor/PotatoProcessor.srcs/sources_1/imports/potato/src/pp_csr_alu.vhd
  R:/Users/Mitchell/Documents/Academics/PotatoProcessor/PotatoProcessor.srcs/sources_1/imports/potato/src/pp_execute.vhd
  R:/Users/Mitchell/Documents/Academics/PotatoProcessor/PotatoProcessor.srcs/sources_1/imports/potato/src/pp_memory.vhd
  R:/Users/Mitchell/Documents/Academics/PotatoProcessor/PotatoProcessor.srcs/sources_1/imports/potato/src/pp_writeback.vhd
  R:/Users/Mitchell/Documents/Academics/PotatoProcessor/PotatoProcessor.srcs/sources_1/imports/potato/src/pp_core.vhd
  R:/Users/Mitchell/Documents/Academics/PotatoProcessor/PotatoProcessor.srcs/sources_1/imports/potato/soc/pp_fifo.vhd
  R:/Users/Mitchell/Documents/Academics/PotatoProcessor/PotatoProcessor.srcs/sources_1/imports/potato/src/pp_icache.vhd
  R:/Users/Mitchell/Documents/Academics/PotatoProcessor/PotatoProcessor.srcs/sources_1/imports/potato/src/pp_wb_adapter.vhd
  R:/Users/Mitchell/Documents/Academics/PotatoProcessor/PotatoProcessor.srcs/sources_1/imports/potato/src/pp_wb_arbiter.vhd
  R:/Users/Mitchell/Documents/Academics/PotatoProcessor/PotatoProcessor.srcs/sources_1/imports/potato/src/pp_potato.vhd
  R:/Users/Mitchell/Documents/Academics/PotatoProcessor/PotatoProcessor.srcs/sources_1/imports/potato/soc/pp_soc_gpio.vhd
  R:/Users/Mitchell/Documents/Academics/PotatoProcessor/PotatoProcessor.srcs/sources_1/imports/potato/soc/pp_soc_intercon.vhd
  R:/Users/Mitchell/Documents/Academics/PotatoProcessor/PotatoProcessor.srcs/sources_1/imports/potato/soc/pp_soc_memory.vhd
  R:/Users/Mitchell/Documents/Academics/PotatoProcessor/PotatoProcessor.srcs/sources_1/imports/potato/soc/pp_soc_reset.vhd
  R:/Users/Mitchell/Documents/Academics/PotatoProcessor/PotatoProcessor.srcs/sources_1/imports/potato/soc/pp_soc_timer.vhd
  R:/Users/Mitchell/Documents/Academics/PotatoProcessor/PotatoProcessor.srcs/sources_1/imports/potato/soc/pp_soc_uart.vhd
  R:/Users/Mitchell/Documents/Academics/PotatoProcessor/PotatoProcessor.srcs/sources_1/imports/potato/example/toplevel.vhd
}
read_ip -quiet R:/Users/Mitchell/Documents/Academics/PotatoProcessor/PotatoProcessor.srcs/sources_1/ip/aee_rom/aee_rom.xci
set_property used_in_implementation false [get_files -all r:/Users/Mitchell/Documents/Academics/PotatoProcessor/PotatoProcessor.gen/sources_1/ip/aee_rom/aee_rom_ooc.xdc]

read_ip -quiet R:/Users/Mitchell/Documents/Academics/PotatoProcessor/PotatoProcessor.srcs/sources_1/ip/clock_generator/clock_generator.xci
set_property used_in_implementation false [get_files -all r:/Users/Mitchell/Documents/Academics/PotatoProcessor/PotatoProcessor.gen/sources_1/ip/clock_generator/clock_generator_board.xdc]
set_property used_in_implementation false [get_files -all r:/Users/Mitchell/Documents/Academics/PotatoProcessor/PotatoProcessor.gen/sources_1/ip/clock_generator/clock_generator.xdc]
set_property used_in_implementation false [get_files -all r:/Users/Mitchell/Documents/Academics/PotatoProcessor/PotatoProcessor.gen/sources_1/ip/clock_generator/clock_generator_ooc.xdc]
set_property used_in_implementation false [get_files -all r:/Users/Mitchell/Documents/Academics/PotatoProcessor/PotatoProcessor.gen/sources_1/ip/clock_generator/clock_generator_late.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc R:/Users/Mitchell/Documents/Academics/PotatoProcessor/PotatoProcessor.srcs/constrs_1/imports/example/arty.xdc
set_property used_in_implementation false [get_files R:/Users/Mitchell/Documents/Academics/PotatoProcessor/PotatoProcessor.srcs/constrs_1/imports/example/arty.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top toplevel -part xc7s50csga324-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef toplevel.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file toplevel_utilization_synth.rpt -pb toplevel_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
