# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Arty-S7-50-Master.xdc

# Block Designs: bd/FFTAudio_Block/FFTAudio_Block.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FFTAudio_Block || ORIG_REF_NAME==FFTAudio_Block} -quiet] -quiet

# IP: bd/FFTAudio_Block/ip/FFTAudio_Block_microblaze_0_1/FFTAudio_Block_microblaze_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FFTAudio_Block_microblaze_0_1 || ORIG_REF_NAME==FFTAudio_Block_microblaze_0_1} -quiet] -quiet

# IP: bd/FFTAudio_Block/ip/FFTAudio_Block_dlmb_v10_1/FFTAudio_Block_dlmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FFTAudio_Block_dlmb_v10_1 || ORIG_REF_NAME==FFTAudio_Block_dlmb_v10_1} -quiet] -quiet

# IP: bd/FFTAudio_Block/ip/FFTAudio_Block_ilmb_v10_1/FFTAudio_Block_ilmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FFTAudio_Block_ilmb_v10_1 || ORIG_REF_NAME==FFTAudio_Block_ilmb_v10_1} -quiet] -quiet

# IP: bd/FFTAudio_Block/ip/FFTAudio_Block_dlmb_bram_if_cntlr_1/FFTAudio_Block_dlmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FFTAudio_Block_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==FFTAudio_Block_dlmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/FFTAudio_Block/ip/FFTAudio_Block_ilmb_bram_if_cntlr_1/FFTAudio_Block_ilmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FFTAudio_Block_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==FFTAudio_Block_ilmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/FFTAudio_Block/ip/FFTAudio_Block_lmb_bram_1/FFTAudio_Block_lmb_bram_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FFTAudio_Block_lmb_bram_1 || ORIG_REF_NAME==FFTAudio_Block_lmb_bram_1} -quiet] -quiet

# IP: bd/FFTAudio_Block/ip/FFTAudio_Block_xbar_1/FFTAudio_Block_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FFTAudio_Block_xbar_1 || ORIG_REF_NAME==FFTAudio_Block_xbar_1} -quiet] -quiet

# IP: bd/FFTAudio_Block/ip/FFTAudio_Block_microblaze_0_axi_periph_1/FFTAudio_Block_microblaze_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FFTAudio_Block_microblaze_0_axi_periph_1 || ORIG_REF_NAME==FFTAudio_Block_microblaze_0_axi_periph_1} -quiet] -quiet

# IP: bd/FFTAudio_Block/ip/FFTAudio_Block_microblaze_0_axi_intc_0/FFTAudio_Block_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FFTAudio_Block_microblaze_0_axi_intc_0 || ORIG_REF_NAME==FFTAudio_Block_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/FFTAudio_Block/ip/FFTAudio_Block_microblaze_0_xlconcat_0/FFTAudio_Block_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FFTAudio_Block_microblaze_0_xlconcat_0 || ORIG_REF_NAME==FFTAudio_Block_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/FFTAudio_Block/ip/FFTAudio_Block_mdm_1_1/FFTAudio_Block_mdm_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FFTAudio_Block_mdm_1_1 || ORIG_REF_NAME==FFTAudio_Block_mdm_1_1} -quiet] -quiet

# IP: bd/FFTAudio_Block/ip/FFTAudio_Block_clk_wiz_1_0/FFTAudio_Block_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FFTAudio_Block_clk_wiz_1_0 || ORIG_REF_NAME==FFTAudio_Block_clk_wiz_1_0} -quiet] -quiet

# IP: bd/FFTAudio_Block/ip/FFTAudio_Block_rst_clk_wiz_1_100M_0/FFTAudio_Block_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FFTAudio_Block_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==FFTAudio_Block_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/FFTAudio_Block/ip/FFTAudio_Block_axi_uartlite_0_0/FFTAudio_Block_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FFTAudio_Block_axi_uartlite_0_0 || ORIG_REF_NAME==FFTAudio_Block_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/FFTAudio_Block/ip/FFTAudio_Block_axi_iic_0_1/FFTAudio_Block_axi_iic_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FFTAudio_Block_axi_iic_0_1 || ORIG_REF_NAME==FFTAudio_Block_axi_iic_0_1} -quiet] -quiet

# IP: bd/FFTAudio_Block/ip/FFTAudio_Block_axi_gpio_0_0/FFTAudio_Block_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FFTAudio_Block_axi_gpio_0_0 || ORIG_REF_NAME==FFTAudio_Block_axi_gpio_0_0} -quiet] -quiet

# IP: bd/FFTAudio_Block/ip/FFTAudio_Block_xadc_wiz_0_1/FFTAudio_Block_xadc_wiz_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FFTAudio_Block_xadc_wiz_0_1 || ORIG_REF_NAME==FFTAudio_Block_xadc_wiz_0_1} -quiet] -quiet

# IP: bd/FFTAudio_Block/ip/FFTAudio_Block_axi_gpio_1_0/FFTAudio_Block_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FFTAudio_Block_axi_gpio_1_0 || ORIG_REF_NAME==FFTAudio_Block_axi_gpio_1_0} -quiet] -quiet

# IP: bd/FFTAudio_Block/ip/FFTAudio_Block_axi_gpio_2_0/FFTAudio_Block_axi_gpio_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FFTAudio_Block_axi_gpio_2_0 || ORIG_REF_NAME==FFTAudio_Block_axi_gpio_2_0} -quiet] -quiet

# IP: bd/FFTAudio_Block/ip/FFTAudio_Block_xlconstant_0_0/FFTAudio_Block_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FFTAudio_Block_xlconstant_0_0 || ORIG_REF_NAME==FFTAudio_Block_xlconstant_0_0} -quiet] -quiet

# IP: bd/FFTAudio_Block/ip/FFTAudio_Block_reset_inv_0_2/FFTAudio_Block_reset_inv_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FFTAudio_Block_reset_inv_0_2 || ORIG_REF_NAME==FFTAudio_Block_reset_inv_0_2} -quiet] -quiet

# XDC: r:/Users/Mitchell/Documents/GitHub/2021-Hardware/Audio_Spectrum_Analyzer/FPGA/Vivado-FFTAudio/FFTAudio.gen/sources_1/bd/FFTAudio_Block/FFTAudio_Block_ooc.xdc
