# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "R:/Users/Mitchell/Documents/GitHub/2021-Hardware/Audio_Spectrum_Analyzer/FPGA/Vivado-FFTAudio/FFTAudio.runs/synth_1/FFTAudio_Block_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param xicom.use_bs_reader 1
set_msg_config  -id {[BD 41-1306]}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7s50csga324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir R:/Users/Mitchell/Documents/GitHub/2021-Hardware/Audio_Spectrum_Analyzer/FPGA/Vivado-FFTAudio/FFTAudio.cache/wt [current_project]
set_property parent.project_path R:/Users/Mitchell/Documents/GitHub/2021-Hardware/Audio_Spectrum_Analyzer/FPGA/Vivado-FFTAudio/FFTAudio.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part_repo_paths {C:/Users/Mitchell/AppData/Roaming/Xilinx/Vivado/2020.2/xhub/board_store/xilinx_board_store} [current_project]
set_property board_part digilentinc.com:arty-s7-50:part0:1.0 [current_project]
set_property ip_output_repo r:/Users/Mitchell/Documents/GitHub/2021-Hardware/Audio_Spectrum_Analyzer/FPGA/Vivado-FFTAudio/FFTAudio.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib R:/Users/Mitchell/Documents/GitHub/2021-Hardware/Audio_Spectrum_Analyzer/FPGA/Vivado-FFTAudio/FFTAudio.gen/sources_1/bd/FFTAudio_Block/hdl/FFTAudio_Block_wrapper.v
add_files R:/Users/Mitchell/Documents/GitHub/2021-Hardware/Audio_Spectrum_Analyzer/FPGA/Vivado-FFTAudio/FFTAudio.srcs/sources_1/bd/FFTAudio_Block/FFTAudio_Block.bd
set_property used_in_implementation false [get_files -all r:/Users/Mitchell/Documents/GitHub/2021-Hardware/Audio_Spectrum_Analyzer/FPGA/Vivado-FFTAudio/FFTAudio.gen/sources_1/bd/FFTAudio_Block/ip/FFTAudio_Block_microblaze_0_1/FFTAudio_Block_microblaze_0_1.xdc]
set_property used_in_implementation false [get_files -all r:/Users/Mitchell/Documents/GitHub/2021-Hardware/Audio_Spectrum_Analyzer/FPGA/Vivado-FFTAudio/FFTAudio.gen/sources_1/bd/FFTAudio_Block/ip/FFTAudio_Block_microblaze_0_1/FFTAudio_Block_microblaze_0_1_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all r:/Users/Mitchell/Documents/GitHub/2021-Hardware/Audio_Spectrum_Analyzer/FPGA/Vivado-FFTAudio/FFTAudio.gen/sources_1/bd/FFTAudio_Block/ip/FFTAudio_Block_microblaze_0_1/FFTAudio_Block_microblaze_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all r:/Users/Mitchell/Documents/GitHub/2021-Hardware/Audio_Spectrum_Analyzer/FPGA/Vivado-FFTAudio/FFTAudio.gen/sources_1/bd/FFTAudio_Block/ip/FFTAudio_Block_dlmb_v10_1/FFTAudio_Block_dlmb_v10_1_ooc.xdc]
set_property used_in_implementation false [get_files -all r:/Users/Mitchell/Documents/GitHub/2021-Hardware/Audio_Spectrum_Analyzer/FPGA/Vivado-FFTAudio/FFTAudio.gen/sources_1/bd/FFTAudio_Block/ip/FFTAudio_Block_ilmb_v10_1/FFTAudio_Block_ilmb_v10_1_ooc.xdc]
set_property used_in_implementation false [get_files -all r:/Users/Mitchell/Documents/GitHub/2021-Hardware/Audio_Spectrum_Analyzer/FPGA/Vivado-FFTAudio/FFTAudio.gen/sources_1/bd/FFTAudio_Block/ip/FFTAudio_Block_dlmb_bram_if_cntlr_1/FFTAudio_Block_dlmb_bram_if_cntlr_1_ooc.xdc]
set_property used_in_implementation false [get_files -all r:/Users/Mitchell/Documents/GitHub/2021-Hardware/Audio_Spectrum_Analyzer/FPGA/Vivado-FFTAudio/FFTAudio.gen/sources_1/bd/FFTAudio_Block/ip/FFTAudio_Block_ilmb_bram_if_cntlr_1/FFTAudio_Block_ilmb_bram_if_cntlr_1_ooc.xdc]
set_property used_in_implementation false [get_files -all r:/Users/Mitchell/Documents/GitHub/2021-Hardware/Audio_Spectrum_Analyzer/FPGA/Vivado-FFTAudio/FFTAudio.gen/sources_1/bd/FFTAudio_Block/ip/FFTAudio_Block_lmb_bram_1/FFTAudio_Block_lmb_bram_1_ooc.xdc]
set_property used_in_implementation false [get_files -all r:/Users/Mitchell/Documents/GitHub/2021-Hardware/Audio_Spectrum_Analyzer/FPGA/Vivado-FFTAudio/FFTAudio.gen/sources_1/bd/FFTAudio_Block/ip/FFTAudio_Block_xbar_1/FFTAudio_Block_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all r:/Users/Mitchell/Documents/GitHub/2021-Hardware/Audio_Spectrum_Analyzer/FPGA/Vivado-FFTAudio/FFTAudio.gen/sources_1/bd/FFTAudio_Block/ip/FFTAudio_Block_microblaze_0_axi_intc_0/FFTAudio_Block_microblaze_0_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all r:/Users/Mitchell/Documents/GitHub/2021-Hardware/Audio_Spectrum_Analyzer/FPGA/Vivado-FFTAudio/FFTAudio.gen/sources_1/bd/FFTAudio_Block/ip/FFTAudio_Block_microblaze_0_axi_intc_0/FFTAudio_Block_microblaze_0_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all r:/Users/Mitchell/Documents/GitHub/2021-Hardware/Audio_Spectrum_Analyzer/FPGA/Vivado-FFTAudio/FFTAudio.gen/sources_1/bd/FFTAudio_Block/ip/FFTAudio_Block_microblaze_0_axi_intc_0/FFTAudio_Block_microblaze_0_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all r:/Users/Mitchell/Documents/GitHub/2021-Hardware/Audio_Spectrum_Analyzer/FPGA/Vivado-FFTAudio/FFTAudio.gen/sources_1/bd/FFTAudio_Block/ip/FFTAudio_Block_mdm_1_1/FFTAudio_Block_mdm_1_1.xdc]
set_property used_in_implementation false [get_files -all r:/Users/Mitchell/Documents/GitHub/2021-Hardware/Audio_Spectrum_Analyzer/FPGA/Vivado-FFTAudio/FFTAudio.gen/sources_1/bd/FFTAudio_Block/ip/FFTAudio_Block_mdm_1_1/FFTAudio_Block_mdm_1_1_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all r:/Users/Mitchell/Documents/GitHub/2021-Hardware/Audio_Spectrum_Analyzer/FPGA/Vivado-FFTAudio/FFTAudio.gen/sources_1/bd/FFTAudio_Block/ip/FFTAudio_Block_clk_wiz_1_0/FFTAudio_Block_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all r:/Users/Mitchell/Documents/GitHub/2021-Hardware/Audio_Spectrum_Analyzer/FPGA/Vivado-FFTAudio/FFTAudio.gen/sources_1/bd/FFTAudio_Block/ip/FFTAudio_Block_clk_wiz_1_0/FFTAudio_Block_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all r:/Users/Mitchell/Documents/GitHub/2021-Hardware/Audio_Spectrum_Analyzer/FPGA/Vivado-FFTAudio/FFTAudio.gen/sources_1/bd/FFTAudio_Block/ip/FFTAudio_Block_clk_wiz_1_0/FFTAudio_Block_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all r:/Users/Mitchell/Documents/GitHub/2021-Hardware/Audio_Spectrum_Analyzer/FPGA/Vivado-FFTAudio/FFTAudio.gen/sources_1/bd/FFTAudio_Block/ip/FFTAudio_Block_rst_clk_wiz_1_100M_0/FFTAudio_Block_rst_clk_wiz_1_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all r:/Users/Mitchell/Documents/GitHub/2021-Hardware/Audio_Spectrum_Analyzer/FPGA/Vivado-FFTAudio/FFTAudio.gen/sources_1/bd/FFTAudio_Block/ip/FFTAudio_Block_rst_clk_wiz_1_100M_0/FFTAudio_Block_rst_clk_wiz_1_100M_0.xdc]
set_property used_in_implementation false [get_files -all r:/Users/Mitchell/Documents/GitHub/2021-Hardware/Audio_Spectrum_Analyzer/FPGA/Vivado-FFTAudio/FFTAudio.gen/sources_1/bd/FFTAudio_Block/ip/FFTAudio_Block_rst_clk_wiz_1_100M_0/FFTAudio_Block_rst_clk_wiz_1_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all r:/Users/Mitchell/Documents/GitHub/2021-Hardware/Audio_Spectrum_Analyzer/FPGA/Vivado-FFTAudio/FFTAudio.gen/sources_1/bd/FFTAudio_Block/ip/FFTAudio_Block_axi_uartlite_0_0/FFTAudio_Block_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all r:/Users/Mitchell/Documents/GitHub/2021-Hardware/Audio_Spectrum_Analyzer/FPGA/Vivado-FFTAudio/FFTAudio.gen/sources_1/bd/FFTAudio_Block/ip/FFTAudio_Block_axi_uartlite_0_0/FFTAudio_Block_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all r:/Users/Mitchell/Documents/GitHub/2021-Hardware/Audio_Spectrum_Analyzer/FPGA/Vivado-FFTAudio/FFTAudio.gen/sources_1/bd/FFTAudio_Block/ip/FFTAudio_Block_axi_uartlite_0_0/FFTAudio_Block_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all r:/Users/Mitchell/Documents/GitHub/2021-Hardware/Audio_Spectrum_Analyzer/FPGA/Vivado-FFTAudio/FFTAudio.gen/sources_1/bd/FFTAudio_Block/ip/FFTAudio_Block_axi_iic_0_1/FFTAudio_Block_axi_iic_0_1_board.xdc]
set_property used_in_implementation false [get_files -all r:/Users/Mitchell/Documents/GitHub/2021-Hardware/Audio_Spectrum_Analyzer/FPGA/Vivado-FFTAudio/FFTAudio.gen/sources_1/bd/FFTAudio_Block/ip/FFTAudio_Block_axi_iic_0_1/FFTAudio_Block_axi_iic_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all r:/Users/Mitchell/Documents/GitHub/2021-Hardware/Audio_Spectrum_Analyzer/FPGA/Vivado-FFTAudio/FFTAudio.gen/sources_1/bd/FFTAudio_Block/ip/FFTAudio_Block_axi_gpio_0_0/FFTAudio_Block_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all r:/Users/Mitchell/Documents/GitHub/2021-Hardware/Audio_Spectrum_Analyzer/FPGA/Vivado-FFTAudio/FFTAudio.gen/sources_1/bd/FFTAudio_Block/ip/FFTAudio_Block_axi_gpio_0_0/FFTAudio_Block_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all r:/Users/Mitchell/Documents/GitHub/2021-Hardware/Audio_Spectrum_Analyzer/FPGA/Vivado-FFTAudio/FFTAudio.gen/sources_1/bd/FFTAudio_Block/ip/FFTAudio_Block_axi_gpio_0_0/FFTAudio_Block_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all r:/Users/Mitchell/Documents/GitHub/2021-Hardware/Audio_Spectrum_Analyzer/FPGA/Vivado-FFTAudio/FFTAudio.gen/sources_1/bd/FFTAudio_Block/ip/FFTAudio_Block_xadc_wiz_0_1/FFTAudio_Block_xadc_wiz_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all r:/Users/Mitchell/Documents/GitHub/2021-Hardware/Audio_Spectrum_Analyzer/FPGA/Vivado-FFTAudio/FFTAudio.gen/sources_1/bd/FFTAudio_Block/ip/FFTAudio_Block_xadc_wiz_0_1/FFTAudio_Block_xadc_wiz_0_1.xdc]
set_property used_in_implementation false [get_files -all r:/Users/Mitchell/Documents/GitHub/2021-Hardware/Audio_Spectrum_Analyzer/FPGA/Vivado-FFTAudio/FFTAudio.gen/sources_1/bd/FFTAudio_Block/ip/FFTAudio_Block_axi_gpio_1_0/FFTAudio_Block_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all r:/Users/Mitchell/Documents/GitHub/2021-Hardware/Audio_Spectrum_Analyzer/FPGA/Vivado-FFTAudio/FFTAudio.gen/sources_1/bd/FFTAudio_Block/ip/FFTAudio_Block_axi_gpio_1_0/FFTAudio_Block_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all r:/Users/Mitchell/Documents/GitHub/2021-Hardware/Audio_Spectrum_Analyzer/FPGA/Vivado-FFTAudio/FFTAudio.gen/sources_1/bd/FFTAudio_Block/ip/FFTAudio_Block_axi_gpio_1_0/FFTAudio_Block_axi_gpio_1_0.xdc]
set_property used_in_implementation false [get_files -all r:/Users/Mitchell/Documents/GitHub/2021-Hardware/Audio_Spectrum_Analyzer/FPGA/Vivado-FFTAudio/FFTAudio.gen/sources_1/bd/FFTAudio_Block/ip/FFTAudio_Block_axi_gpio_2_0/FFTAudio_Block_axi_gpio_2_0_board.xdc]
set_property used_in_implementation false [get_files -all r:/Users/Mitchell/Documents/GitHub/2021-Hardware/Audio_Spectrum_Analyzer/FPGA/Vivado-FFTAudio/FFTAudio.gen/sources_1/bd/FFTAudio_Block/ip/FFTAudio_Block_axi_gpio_2_0/FFTAudio_Block_axi_gpio_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all r:/Users/Mitchell/Documents/GitHub/2021-Hardware/Audio_Spectrum_Analyzer/FPGA/Vivado-FFTAudio/FFTAudio.gen/sources_1/bd/FFTAudio_Block/ip/FFTAudio_Block_axi_gpio_2_0/FFTAudio_Block_axi_gpio_2_0.xdc]
set_property used_in_implementation false [get_files -all r:/Users/Mitchell/Documents/GitHub/2021-Hardware/Audio_Spectrum_Analyzer/FPGA/Vivado-FFTAudio/FFTAudio.gen/sources_1/bd/FFTAudio_Block/FFTAudio_Block_ooc.xdc]
set_property used_in_implementation false [get_files -all r:/Users/Mitchell/Documents/GitHub/2021-Hardware/Audio_Spectrum_Analyzer/FPGA/Vivado-FFTAudio/FFTAudio.gen/sources_1/bd/FFTAudio_Block/ip/FFTAudio_Block_microblaze_0_1/data/mb_bootloop_le.elf]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc R:/Users/Mitchell/Documents/GitHub/2021-Hardware/Audio_Spectrum_Analyzer/FPGA/Vivado-FFTAudio/FFTAudio.srcs/constrs_1/new/Arty-S7-50-Master.xdc
set_property used_in_implementation false [get_files R:/Users/Mitchell/Documents/GitHub/2021-Hardware/Audio_Spectrum_Analyzer/FPGA/Vivado-FFTAudio/FFTAudio.srcs/constrs_1/new/Arty-S7-50-Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top FFTAudio_Block_wrapper -part xc7s50csga324-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef FFTAudio_Block_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file FFTAudio_Block_wrapper_utilization_synth.rpt -pb FFTAudio_Block_wrapper_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
